### ISSUE TITLE
Santos' files.

### ISSUE THREAD

**Issue by Ternal-AprilJoy** [PUP-BSIT/ex9-avengears#1]
**Do a descriptive naming on your classes. Name your classes according to its content/purpose.**  

You may not appreciate it now since you're working with few classes, but this practice will make your code more readable, especially when your project gets more complicated later on.

Think of it like giving each class a label so you can find what you need quickly. 

for example:

`<div class="gallery">  `

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/santos_akishagelsey/index.html#L27

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/santos_akishagelsey/index.html#L40

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/santos_akishagelsey/index.html#L58

**Comment by Ternal-AprilJoy** [comment]
You can set the `href` attribute of hyperlinks to `#` if it doesn't have any content or not existing. 

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/santos_akishagelsey/index.html#L43-L47

It's a small but significant detail for usability and accessibility of your website.

**Comment by Villa-VillaDiana** [comment]
Observe proper indentation. Please check [issue #11  ](https://github.com/PUP-BSIT/ex9-avengears/issues/11#issue-2245400640)to help you to prevent this in the future.https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/santos_akishagelsey/index.html#L3-L8
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/santos_akishagelsey/index.html#L9-L99

**Comment by Villa-VillaDiana** [comment]
Instead of placing the img:hover at the end of your code, you might want to position it right after your img selector. It is good practice to have your related codes/elements in sequence. This will be beneficial in the future as your codes become longer. 
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/santos_akishagelsey/style.css#L45-L53
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/santos_akishagelsey/style.css#L156-L158

**Comment by Villa-VillaDiana** [comment]
I noticed that you used the ‘height’ declaration twice to format your image. The ‘160px’ will be overwritten by the second declaration. Please consider removing one of the declarations.
**Reference**: https://vecta.io/blog/definitive-guide-to-css-styling-order#:~:text=CSS%20rules%20always%20prioritize%20from,then%20from%20top%20to%20bottom.
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/santos_akishagelsey/style.css#L47
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/santos_akishagelsey/style.css#L51

Same issue with:
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/santos_akishagelsey/style.css#L90
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/santos_akishagelsey/style.css#L94

Duplicate declaration:
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/santos_akishagelsey/style.css#L93
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/santos_akishagelsey/style.css#L97

**Comment by santosakishagelsey** [comment]
thank you
