### ISSUE TITLE
Website Functionality and Appearance

### ISSUE THREAD

**Issue by Villa-VillaDiana** [PUP-BSIT/ex9-avengears#10]
These are the compiled issues that address the functionality and appearance of your site

**Comment by Villa-VillaDiana** [comment]
The links are not working because you guys changed your HTML file to "**index.html**"
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/ferolino_jasmin/index.html#L14-L22
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/malapad_melchorjames/index.html#L17-L25
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/japitana_johnwalter/index.html#L19-L27
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/santos_akishagelsey/index.html#L15-L23

**Comment by Villa-VillaDiana** [comment]
These are some of my layout suggestions for your websites. This is to prevent the awkward white space you have.
You may choose only one of the layouts here, or mix and match the layouts. 
**References**: https://www.commoninja.com/blog/guide-to-website-layouts#Understanding-the-Basics-of-Website-Layouts
https://www.w3schools.com/css/css_grid.asp 
https://www.w3schools.com/howto/howto_css_cards.asp


![Layout_1](https://github.com/PUP-BSIT/ex9-avengears/assets/146617812/b7d14a6c-9940-4d61-9d12-c876fe86fbcf)
![Layout_2](https://github.com/PUP-BSIT/ex9-avengears/assets/146617812/01df80ab-d805-4fbe-b63f-c56a8fe5efd7)

**Comment by Villa-VillaDiana** [comment]
**Color Contrast**
Be mindful of the colors you use because some text on your website is hard to read. To check the color contrast of your work, you can visit the [WebAim Contrast Checker](https://webaim.org/resources/contrastchecker/). The ideal contrast ratio is 4.5. In the attachment below, you will see the difference that good contrast makes.

In this example, you can see that the text is hard to read.
![Screenshot 2024-04-16 190406](https://github.com/PUP-BSIT/ex9-avengears/assets/146617812/1bd3e969-c91e-440f-a634-9664a3bc84dd)
If we check the contrast ratio, it only reaches 1.36. We can solve this by adjusting the color of either of the two. 
![Screenshot 2024-04-16 190722](https://github.com/PUP-BSIT/ex9-avengears/assets/146617812/3f7c62a7-bda5-495d-926c-86e0330edc9d)
In this case, I adjusted the color of the text.
![Screenshot 2024-04-16 191008](https://github.com/PUP-BSIT/ex9-avengears/assets/146617812/566df46c-b70d-4e19-be19-d6c967d7744b)

**Comment by ferolinojasmin** [comment]
Thank you!
