### ISSUE TITLE
Formatting Tips

### ISSUE THREAD

**Issue by Ternal-AprilJoy** [PUP-BSIT/ex9-avengears#11]
### **PRETTIER**

Since some of you guys are still exceeding the 80 col and also still having issues with indentation, I would like to share a tip on how I efficiently use prettier :)

1. First go to settings>then search "format"
2. Set your **default formatter** to Prettier.
3. Check the **"Format on Save"** option. 

This will be helpful since each time you save your file, your code gets to be formatted automatically.

For a visual guide, you can watch a quick 3-minute tutorial on YouTube: [Prettier Visual Code Format on Save](https://www.youtube.com/results?search_query=prettier+visual+code+format+on+save)

**Comment by Ternal-AprilJoy** [comment]
### **Live Preview Extension**

Install Live Preview (by Microsoft) extension. 

This will be a big help as you won't need to switch back from your browser and editor every time you want to see your design changes. 

Once installed, there will be a button on the upper right side. 
![Screenshot 2024-04-16 163704](https://github.com/PUP-BSIT/ex9-avengears/assets/146558022/ce266103-4f3a-41ed-9254-154d5f8dce90)


And it will give a preview on what your website looks like **real-time.**
![image](https://github.com/PUP-BSIT/ex9-avengears/assets/146558022/39e5532e-94c1-49de-b12d-0d836ae1416b)



Our group noticed that almost all of your outputs look exactly the same. This extension will make your website designing smoother and more enjoyable. :) 


ps: live server by ritwick dey is a good extension too but i would recommend using this since it's more convenient for beginners.

**Comment by ferolinojasmin** [comment]
Thank you!
