### ISSUE TITLE
Additional Issues Related to Ferolino’s File

### ISSUE THREAD

**Issue by Villa-VillaDiana** [PUP-BSIT/ex9-avengears#12]
The ‘li-’ seems to be out of place. Please remove unnecessary text.
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/ferolino_jasmin/index.html#L12

**Comment by Villa-VillaDiana** [comment]
I noticed that you used the ‘display’ declaration twice to format your gallery. The ‘inline’ will be overwritten by the second declaration. Please consider removing one of the declarations.
Reference: https://vecta.io/blog/definitive-guide-to-css-styling-order#:~:text=CSS%20rules%20always%20prioritize%20from,then%20from%20top%20to%20bottom.

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/ferolino_jasmin/style.css#L91
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/ferolino_jasmin/style.css#L95
Duplicate declaration:
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/ferolino_jasmin/style.css#L94
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/ferolino_jasmin/style.css#L98

**Comment by ferolinojasmin** [comment]
Thank you!
