### ISSUE TITLE
Issues Related to Your Index file

### ISSUE THREAD

**Issue by Villa-VillaDiana** [PUP-BSIT/ex9-avengears#13]
Observe proper indentation Please check [issue #11  ](https://github.com/PUP-BSIT/ex9-avengears/issues/11#issue-2245400640)to help you to prevent this in the future.
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/index.html#L3-L6
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/index.html#L7-L23
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/style.css#L8-L11

**Comment by Villa-VillaDiana** [comment]
Please remove unused styles.
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/style.css#L175-L226

**Comment by Japitana-JohnWalter** [comment]
thank you
