### ISSUE TITLE
Class name

### ISSUE THREAD

**Issue by MentokAlmera** [PUP-BSIT/ex9-avengears#2]
Class names should be all lower case.
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/ferolino_jasmin/index.html#L39

**Comment by Japitana-JohnWalter** [comment]
thank you
