### ISSUE TITLE
adding line spaces 

### ISSUE THREAD

**Issue by MentokAlmera** [PUP-BSIT/ex9-avengears#3]
Adding lines spaces between code groups for readability

https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g29e6ce31160_0_35

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/ferolino_jasmin/index.html#L8C3-L64C15

**Comment by ferolinojasmin** [comment]
Thank you!
