### ISSUE TITLE
Retyping the entire header section <head> 

### ISSUE THREAD

**Issue by MentokAlmera** [PUP-BSIT/ex9-avengears#4]
Retyping the entire header section <head> for each HTML file is not considered a good practice. Instead, you should create a separate HTML file that contains the common header code and then link to it from each of your HTML files using the <link> tag. 

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/ferolino_jasmin/index.html#L68C1-L117C8

**Comment by ferolinojasmin** [comment]
Thank you!
