### ISSUE TITLE
Proper indentation

### ISSUE THREAD

**Issue by MentokAlmera** [PUP-BSIT/ex9-avengears#5]
Observe proper indentation.

https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_50

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/ferolino_jasmin/style.css#L18C2-L34C4

**Comment by Villa-VillaDiana** [comment]
Same issue with: 
Please check [issue #11  ](https://github.com/PUP-BSIT/ex9-avengears/issues/11#issue-2245400640)to help you to prevent this in the future.
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/ferolino_jasmin/index.html#L3-L7
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/ferolino_jasmin/index.html#L8-L65

**Comment by ferolinojasmin** [comment]
Thank you!
