### ISSUE TITLE
single space

### ISSUE THREAD

**Issue by MentokAlmera** [PUP-BSIT/ex9-avengears#6]
Separate every css block with a single space.

https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/ferolino_jasmin/style.css#L34C1-L37C4

**Comment by ferolinojasmin** [comment]
Thank you!
