### ISSUE TITLE
space after the selector

### ISSUE THREAD

**Issue by MentokAlmera** [PUP-BSIT/ex9-avengears#7]
Add a single space after the selector/s and before "{".

https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24acb740da7_0_35

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/ferolino_jasmin/style.css#L42C1-L42C6

**Comment by ferolinojasmin** [comment]
Thank you!
