### ISSUE TITLE
Malapad's Files

### ISSUE THREAD

**Issue by Tapispisan-YvesJohn** [PUP-BSIT/ex9-avengears#8]
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/malapad_melchorjames/index.html#L14

All class names should be written in kebab case. 
`<li class="li-class-dropdown">`

See here for reference @Malapad 
https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_5

Edit.
There is nothing wrong with the class name. You are just applying two different class name in the same element but you can apply the issue below on this one. Naming a class in a descriptive way. Just ignore this error and focus on the ones below. Sorry for the misunderstanding and thank you.

**Comment by Tapispisan-YvesJohn** [comment]
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/malapad_melchorjames/index.html#L29

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/malapad_melchorjames/index.html#L42

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/malapad_melchorjames/index.html#L60

When naming a classes, try doing it in a descriptive way. For example, when adding a class name in your div, instead of using class-#number use;
`div class="gallery"`
or any class name that will give its purpose/function/content.

**Comment by Tapispisan-YvesJohn** [comment]
Don't forget to apply the changes in your html class names into your css file selectors.

**Comment by Villa-VillaDiana** [comment]
Observe proper indentation. Please check [issue #11  ](https://github.com/PUP-BSIT/ex9-avengears/issues/11#issue-2245400640)to help you to prevent this in the future.

https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/malapad_melchorjames/index.html#L3-L8
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/malapad_melchorjames/index.html#L9-L101

**Comment by Villa-VillaDiana** [comment]
I noticed that you used the ‘display’ declaration twice to format your image. The ‘center’ will be overwritten by the second declaration. Please consider removing one of the declarations.
Reference: https://vecta.io/blog/definitive-guide-to-css-styling-order#:~:text=CSS%20rules%20always%20prioritize%20from,then%20from%20top%20to%20bottom.
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/malapad_melchorjames/style.css#L49
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/malapad_melchorjames/style.css#L53

Duplicate declaration:
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/malapad_melchorjames/style.css#L52
https://github.com/PUP-BSIT/ex9-avengears/blob/3b962f44afa0b23b8329269a6d93b603954e4bfc/malapad_melchorjames/style.css#L56

**Comment by Malapad** [comment]
thank you
